Rs=1.2; Ld=0.0057; Lq=0.0125;
s = tf('s');
Ts = 1/8000;
lpf_T = 1/2000;
delay_computation = exp(-s*Ts);
delay_output = exp(-s*Ts/2);
tf_filter = tf(2000, [1 2000]);
delay_SH = exp(-s*Ts/2);
d_axis_plant = tf([1/Lq], [1 Rs/Lq]);
pi_controlller = tf([12.5 1200],[1 0]);
pi_controlller_new = tf([6.8727 659.7818],[1 0]);
Go_no_delay = pi_controlller*d_axis_plant;
Go_with_delay = pi_controlller*delay_computation*delay_output*d_axis_plant*tf_filter*delay_SH;
h=bodeoptions;
h.PhaseMatching='on';
h.Title.FontSize = 14;
h.XLabel.FontSize = 14;
h.YLabel.FontSize = 14;
h.TickLabel.FontSize = 14;
bodeplot(Go_no_delay,'-b',Go_with_delay,'-.r',{1,10000},h);
legend('NoDelay','WithDelay');
h = findobj(gcf,'type','line');
set(h,'linewidth',2);
