s=tf('s'); Ts=1/4000;
wsc=100; J=0.00016;
Kp_w=0.1202; Ki_w=18.0657;
tf_pi=tf([Kp_w Ki_w],[1 0]);
tf_plant=tf(1,[J 0]);
tf_currLoop = tf(1000, [1 1000]);
tf_cmdFilter = tf(Ki_w/Kp_w, [1 Ki_w/Kp_w]);
Go_w_PI = tf_pi*tf_currLoop*tf_plant;
Gc_w_PI = Go_w_PI/(1+Go_w_PI);
Gc_w_IP = tf_cmdFilter*Gc_w_PI;
h=bodeoptions;
h.PhaseMatching='on';
h.Title.FontSize = 14;
h.XLabel.FontSize = 14;
h.YLabel.FontSize = 14;
h.TickLabel.FontSize = 14;
bodeplot(Gc_w_IP,'-b',{1,1000},h);
legend('Gc_w-IP');
h = findobj(gcf,'type','line');
set(h,'linewidth',2);
grid on;